version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_grpc
    volumes:
      - ./apps/db/pgdata:/var/lib/postgresql/data
    ports:
      - '5435:5432'
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
